### ISSUE TITLE
NPM authToken is disclosed in YAML conf file

### ISSUE THREAD

**Issue by xzinkus** [nhumrich/toggle-meister#11]
`echo '//npm.canopytax.com/:_authToken="xrWFRKpQUST+6no1HCmddV8mVbGVEOGEWB3NQZKMXPc="' > ~/.npmrc`

The problem is that private NPM packages are accessible with this token and thus are not private.

**Comment by xzinkus** [comment]
See https://www.npmjs.com/package/registry-auth-token

The "Security" note

**Comment by nhumrich** [comment]
I am aware, and dont care since the repo isnt really private anyway.
