### ISSUE TITLE
Allow for uppercase letters in feature name

### ISSUE THREAD

**Issue by internettrans** [nhumrich/toggle-meister#62]
If you do the following:

```sh
http POST :8445/api/features name=testFeature
```

The response will have a feature toggle that is all lower case: `testfeature`.

I think the reason for this is that toggle-meister encourages snake casing instead of camel casing. Seems like it would be nice though to allow users of toggle meister to choose between camelCase and snake_case. And maybe avoids confusion when people do `GET /api/envs/prod/toggles?feature=testFeature` and the response gives them `testfeature` instead of `testFeature.

**Comment by nhumrich** [comment]
funny, this was allowed at one point, then it caused confusion when testfeature and testFeature both existed, so we got rid of the case sensitivity.

We could potentially prevent upper case during creation. I am hesitant to add the sensitivity back in. Any other thoughts?

**Comment by internettrans** [comment]
Yeah if we don't want case sensitivity, I would prefer a validation error on the backend whenever you try to pass in something with an upper case letter. And also validation in the UI that helps the user know that lowercase is the only thing allowed.

**Comment by nhumrich** [comment]
ok, I can make that happen.

**Comment by frehner** [comment]
Just ran into this, I'm pretty sure. An error is shown in the UI, but the error message doesn't tell you why it failed: 

<img width="764" alt="Screen Shot 2019-08-14 at 2 46 04 PM" src="https://user-images.githubusercontent.com/3054066/63055055-4732c600-bea2-11e9-936b-e868ca9baf3b.png">

In other words, I didn't know that camel caps was why this was failing. I thought it was a permission issue or something

**Comment by nhumrich** [comment]
@frehner the backend is returning a more clear error. Perhaps the FE toast could be modified to show the error message from the backend.
